### ISSUE TITLE
Issue importing very large objects

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stix2arango#1]
See the x-mitre-collection object in this bundle

https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack-15.1.json

It is 1000's of lines long.

It does not import when trying to import this bundle using stix2arango (although no warnings are shown)

I suspect Arango might have a limit. If so, we should warn user that some objects were skipped in CLI at end of run, e.g.

x objects inserted successfully
x objects failed

**Comment by fqrious** [comment]
I'll need more info than that, I can see that this object with [86000 lines x-mitre-collection](http://65.109.227.47:8529/_db/test_db_13_database/_admin/aardvark/index.html#collection/myrules2_vertex_collection/x-mitre-collection--1f5f1533-f617-4ca8-9ab4-6a02367fa019) was successfully inserted

**Comment by fqrious** [comment]
![image](https://github.com/muchdogesec/stix2arango/assets/29603874/311cfdcb-a2be-483a-a8ae-8f6b536fa96a)

Ran this and every single object in the file was uploaded

**Comment by himynamesdave** [comment]
Now appears to be working. Must have been a local error, or more likely, user error :)
