### ISSUE TITLE
Strange behaviour for embedded relationships on updates where stix objects remain the same, but stix2arango_note changes

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stix2arango#10]
Test case 4

https://github.com/muchdogesec/stix2arango/blob/optimizations/tests/4-import-detected-because-of-stix2arango-note.md

```sql
RETURN LENGTH(
  FOR doc IN test4_edge_collection
    FILTER doc._is_latest == true
    AND doc._is_ref == true
    AND doc.created_by_ref == "identity--72e906ce-ca1b-5d73-adcd-9ea9eb66a1b4"
    AND doc._stix2arango_note == "test4C"
      RETURN doc
)
```

Should return 

```json
[
  15032
]
```

(the number of embedded relationships in the bundle)

Which it does.

```sql
RETURN LENGTH(
  FOR doc IN test4_edge_collection
    FILTER doc._is_latest == false
    AND doc._is_ref == true
    AND doc.created_by_ref == "identity--72e906ce-ca1b-5d73-adcd-9ea9eb66a1b4"
    AND doc._stix2arango_note == "test4A"
    OR doc._stix2arango_note == "test4B"
      RETURN doc
)
```

Should return

```json
[
  30064
]
```

b/c two updates have happened to ( 15032x2)

but it actually returns

```
[
  30978
]
```

**Comment by fqrious** [comment]
> https://github.com/muchdogesec/stix2arango/blob/optimizations/tests/4-import-detected-because-of-stix2arango-note.md

Link shows 404

**Comment by himynamesdave** [comment]
@fqrious sorry, here: https://github.com/muchdogesec/stix2arango/blob/optimizations/tests/4-update-detected-because-of-stix2arango-note.md
