### ISSUE TITLE
Ensure when vertex object are updated, embedded relationships are updated accordingly

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stix2arango#6]
If user updates an object and also marks for embedded relationships to be created, then any existing embedded relationships (`_is_ref==true`) should be updated accordingly.

https://github.com/muchdogesec/stix2arango/tree/optimizations/docs#updating-embedded-relationships-optional-user-setting

This feature was never actually implemented in the original code base (only the creation of new embedded relationships without the logic to consider old one representing the same relationship).

**Comment by fqrious** [comment]
by update, what do you mean by that?

**Comment by himynamesdave** [comment]
Let's say in first import of a vertex object causes 3 embedded relationships to be created from it.

Lets say vertex object is updated in a new update (stix2arango valid update). 

In such cases, the old 3 embedded relationships should be marked _is_latest==false

And however many embedded relationships in the update should be created with _is_latest==true 

@fqrious

**Comment by himynamesdave** [comment]
I just added test 17 for this @fqrious and it seems to be working as expected, so closing
